class NginxTarget {
  /**
   * @param {ProcessedNginxOptions} options
   */
  constructor(options) {
    this.options = {
      filename: 'nginx.push.conf',
      omitLocation: false,
      index: '', // index.html
      ...options,
    }
  }

  createConfig(assets) {
    const { index, omitLocation } = this.options
    const content = [
      `# Automatically generated by ServerPushWebpackPlugin, don't change it manually
# Please include this file in your nginx web server directive
# \`\`\`
#   include nginx.push.conf;
# \`\`\``]

    if (!omitLocation) {
      content.push(`location = /${index} {`)
    }

    assets.forEach((asset) => {
      content.push(`  http2_push ${asset};`)
    })

    if (!omitLocation) {
      content.push('}')
    }

    return content.join('\n')
  }
}

export default NginxTarget
